
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
          project_id: ${{ secrets.GCP_STORAGE_BUCKET }}
          export_default_credentials: true
      - name: gcp-storage-sync2
        run: gsutil rsync -R site gs://test-bucket-cooperterraform